from flask_restx import Namespace, Resource, fields
from app.services.chatbot_service import generate_chat_response

# Define Namespace
chatbot_ns = Namespace("chatbot", description="Chatbot operations")

# Define Input Model
chatbot_input = chatbot_ns.model(
    "ChatbotInput",
    {
        "prompt": fields.String(required=True, description="Input text for the chatbot"),
        "max_length": fields.Integer(
            required=False, default=100, description="Maximum length of the generated response"
        ),
    },
)

# Define Output Model
chatbot_output = chatbot_ns.model(
    "ChatbotOutput",
    {
        "response": fields.String(description="Response generated by the chatbot"),
    },
)

# Define Chatbot Resource
@chatbot_ns.route("/")
class ChatbotResource(Resource):
    @chatbot_ns.expect(chatbot_input)
    @chatbot_ns.response(200, "Success", chatbot_output)
    @chatbot_ns.response(500, "Internal Server Error")
    def post(self):
        """
        Generate a chat response based on the input prompt.
        """
        try:
            # Parse input data
            data = chatbot_ns.payload
            prompt = data.get("prompt")
            max_length = data.get("max_length", 100)

            # Generate response
            response = generate_chat_response(prompt, max_length=max_length)
            return {"response": response}, 200
        except Exception as e:
            print(f"Error in ChatbotResource: {e}")
            return {"message": "Failed to generate response. Please try again."}, 500
